/*
 * This source file was generated by the Gradle 'init' task
 */
package com.three_amigas.LaundryOps;

import com.three_amigas.LaundryOps.ui.Home;
import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
        Home home = new Home();
        home.setExtendedState(JFrame.MAXIMIZED_BOTH);
        home.setVisible(true);
    }
}
