/*
 * This source file was generated by the Gradle 'init' task
 */
package com.three_amigas.LaundryOps;

import com.three_amigas.LaundryOps.ui.Home;
import com.three_amigas.LaundryOps.ui.Login;
import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
//        Login login = new Login();
//        login.setVisible(true);

        Home homeFrame = new Home();
        homeFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        homeFrame.setVisible(true);
    }
}
